version: "3.9"

services:
  backend:
    build: ./backend
    container_name: opsmind-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: opsmind-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend